Style guide tweaks
ustaxcourt/ef-cms-flexion pull request #1070
Opened 2019-03-12 18:52 UTC by ericsorenson

2019-03-12 20:16 UTC, kkoskelin requested changes
Try providing an aria-label="your description" and I think we'll be good.

2019-03-12 20:16 UTC, kkoskelin commented on web-client/src/views/Interstitial.jsx
> +  <div className="progress-indicator" aria-live="assertive">
OK, but without a message (e.g. aria-description="one moment") the assertive value may not be entirely useful.

2019-03-12 20:17 UTC, ericsorenson commented on web-client/src/views/Interstitial.jsx
> +  <div className="progress-indicator" aria-live="assertive">
Think we should just remove it?

2019-03-13 13:31 UTC, ericsorenson commented on web-client/src/views/Interstitial.jsx
> +  <div className="progress-indicator" aria-live="assertive">
@kkoskelin updated!

2019-03-13 13:44 UTC, kkoskelin approved these changes

2019-03-13 13:46 UTC, merged