testing sonarqube in jenkins
ustaxcourt/ef-cms-flexion pull request #12
Opened 2018-10-15 14:45 UTC by codyseibert

#3 

- Attempt to setup sonar in Jenkins

2018-10-17 15:12 UTC, dubharmonic commented on web-client/src/index.prod.html
> +<html>
This file was deleted in an earlier PR, was there a merge conflict?

2018-10-17 19:44 UTC, kkoskelin requested changes
Just one change required, I think?

2018-10-17 19:44 UTC, kkoskelin commented on serverless-api/src/package.json
> +      "lvoc",
is this supposed to be `lcov`?

2018-10-18 15:27 UTC, kkoskelin approved these changes

2018-10-18 18:21 UTC, merged