126 Case Views
ustaxcourt/ef-cms-flexion pull request #147
Opened 2018-11-07 14:48 UTC by dubharmonic

![image](https://user-images.githubusercontent.com/248694/48138318-b8857e80-e269-11e8-9799-9f66dfa44da6.png)

![image](https://user-images.githubusercontent.com/248694/48138376-d7841080-e269-11e8-9339-ea44c761b4d1.png)

2018-11-07 14:57 UTC, kkoskelin approved these changes

2018-11-07 15:18 UTC, sadlerw requested changes

2018-11-07 15:18 UTC, sadlerw commented on web-client/src/components/CaseDetail.jsx
> +// import * as Pdf from '../images/pdf.svg';
remove?

2018-11-07 15:18 UTC, sadlerw commented on web-client/src/components/CaseDetail.jsx
> +          {caseDetail.petitionerName}, Petitioner v. Commissioner of Internal
So this title might not be valid until the respondent (irs) has actually filed an answer.  Maybe ask Jessica if it's ok to just always have that as the title.

2018-11-07 15:18 UTC, sadlerw commented on web-client/src/components/CaseList.jsx
> +                <a href={'/case-detail/' + item.docketNumber}>
so each case will have a caseId that is a uuid - you should be using that where appropriate but I agree that here docketNumber is better since the user will see it in the url

2018-11-07 15:18 UTC, sadlerw commented on web-client/src/main/index.js
> +        docketNumber: '110001-18',
add caseId as a uuid maybe for completeness

2018-11-07 15:18 UTC, sadlerw commented on web-client/src/components/Dashboard.jsx
> +        <h1>Dashboard</h1>
every h1 needs id="skip-nav-target" tabindex="-1" for keyboard

2018-11-07 15:51 UTC, kkoskelin commented on web-client/src/components/Dashboard.jsx
> +        <h1>Dashboard</h1>
explain `id="skip-nav-target"` ?  I have other questions about your recommendations, perhaps we can discuss.

2018-11-07 15:57 UTC, sadlerw commented on web-client/src/components/Dashboard.jsx
> +        <h1>Dashboard</h1>
when you reload the page and you are keyboard navigating/voiceover there is a "skip to main body" option that you can pick which then lands you on the h1
it's so that you don't have to read through the header on every single page

2018-11-08 22:19 UTC, sadlerw approved these changes

2018-11-08 22:19 UTC, sadlerw commented on web-client/src/components/CaseDetail.jsx
> +          {caseDetail.petitionerName}, Petitioner v. Commissioner of Internal
confirmed this is ok with @JessicaMarine

2018-11-08 22:19 UTC, merged

2018-11-09 15:08 UTC, JessicaMarine commented
@sadlerw  The case caption should be "First Name Last Name, Petitioner v. Commissioner of Internal Revenue, Respondent".  So, under "Petitioner name" on the dashboard, the first and last name should be switched.