837 - Refresh User Token
ustaxcourt/ef-cms-flexion pull request #1540
Opened 2019-04-29 16:51 UTC by codyseibert

2019-04-29 17:29 UTC, kkoskelin commented on web-client/src/router.js
> +    route('/idle-logout', () => {
Please add this route to a pa11y URL if possible.

2019-04-29 17:34 UTC, kkoskelin approved these changes
Just one question, but looks good!

2019-04-29 17:34 UTC, kkoskelin commented on web-client/src/views/WorkQueue.jsx
> +            onClick={() => refreshTokenSequence()}
was this change done for the sake of testing? otherwise I'm unsure why this occurred.

2019-04-30 12:36 UTC, codyseibert commented on web-client/src/views/WorkQueue.jsx
> +            onClick={() => refreshTokenSequence()}
yeah, local testing, I reverted

2019-04-30 12:38 UTC, codyseibert commented on web-client/src/router.js
> +    route('/idle-logout', () => {
added

2019-04-30 13:57 UTC, kkoskelin approved these changes

2019-04-30 15:37 UTC, ericsorenson commented on web-client/src/applicationContext.js
> +    REFRESH_INTERVAL: 60 * 20 * 1000, // 20 minutes
👍

2019-04-30 15:38 UTC, ericsorenson commented on web-client/src/presenter/actions/setTokenAction.js
>    window.localStorage.setItem('token', JSON.stringify(props.token));
Localstorage access should happen via the applicationContext so that we can mock it

2019-04-30 15:41 UTC, ericsorenson commented on web-client/src/views/IdleActivityMonitor.jsx
> +        {showModal == 'AppTimeoutModal' && !!currentUser && <AppTimeoutModal />}
should be a computed

2019-04-30 15:49 UTC, matthopson commented on web-client/src/presenter/actions/setTokenAction.js
>    window.localStorage.setItem('token', JSON.stringify(props.token));
Do we need to be able to mock it? We actually talked about removing it completely from LS.

2019-04-30 16:27 UTC, kkoskelin requested changes

2019-04-30 16:27 UTC, kkoskelin commented on web-client/src/views/IdleActivityMonitor.jsx
> +    showModal,
showModal has been removed from the 'connect' call?

2019-04-30 16:27 UTC, kkoskelin commented on web-client/src/views/IdleActivityMonitor.jsx
> +    showModal,
also, 'debounce' is being connected but not used.

2019-04-30 17:13 UTC, kkoskelin commented on web-client/src/views/IdleActivityMonitor.jsx
> +    debounce: state.debounce,
'debounce' appears unused

2019-04-30 17:33 UTC, kkoskelin approved these changes

2019-04-30 18:56 UTC, ericsorenson approved these changes

2019-04-30 18:57 UTC, merged