1660 - fixing the colors on the alerts
ustaxcourt/ef-cms-flexion pull request #1841
Opened 2019-05-21 21:01 UTC by codyseibert

2019-05-21 21:30 UTC, rachaelparris requested changes
A few of the colors you added are in the USWDS color variables here: https://v2.designsystem.digital.gov/design-tokens/color/theme-tokens/

2019-05-21 21:30 UTC, rachaelparris commented on web-client/src/styles/variables.scss
> +$color-red: #d83933;
There's a color variable for this red: `$theme-color-secondary`.

2019-05-21 21:30 UTC, rachaelparris commented on web-client/src/styles/variables.scss
> +$color-error: #f8dfe2;
This one is `$theme-color-secondary-lighter`.

2019-05-21 21:30 UTC, rachaelparris commented on web-client/src/styles/variables.scss
> +$color-info-darker: #28a0cb;
This one is `$theme-color-accent-cool-dark`.

2019-05-22 13:28 UTC, kkoskelin approved these changes

2019-05-22 14:11 UTC, rachaelparris approved these changes

2019-05-22 14:11 UTC, merged