1335 paper case timezone fix
ustaxcourt/ef-cms-flexion pull request #2072
Opened 2019-06-14 20:18 UTC by ericsorenson

2019-06-14 20:31 UTC, rachaelparris commented on web-client/src/presenter/actions/createCaseFromPaperAction.js
> +      receivedAt: props.computedDate,
Things make so much more sense now! `checkDate` was converting to an ISO string. So if you want this to still be stored as a full ISO string with the time instead of just a date, I think you will need to do something like 
```  
const receivedAt = 
    (props.computedDate &&
      applicationContext
        .getUtilities()
        .prepareDateFromString(props.computedDate)
        .toISOString()) ||
    null;
``` 
the same as was done in `createTrialSessionAction.js`.

2019-06-17 13:49 UTC, kkoskelin requested changes
Exactly as Rachael has said -- only that fix will probably reside in `computeDateFormAction`.

2019-06-17 15:37 UTC, kkoskelin approved these changes

2019-06-17 15:37 UTC, kkoskelin approved these changes

2019-06-17 15:38 UTC, kkoskelin approved these changes

2019-06-17 15:54 UTC, kkoskelin approved these changes

2019-06-17 16:03 UTC, merged