127 pay.gov
ustaxcourt/ef-cms-flexion pull request #211
Opened 2018-11-26 21:17 UTC by dubharmonic

2018-11-26 22:20 UTC, kkoskelin requested changes

2018-11-26 22:20 UTC, kkoskelin commented on web-client/src/main/actions/setCurrentPage.js
> +    store.set(state.currentPage, page);
![](https://i.chzbgr.com/full/5931830272/h6B99D495/)

2018-11-26 22:20 UTC, kkoskelin commented on web-client/src/components/ValidateCase.jsx
> +                  <input id="paygov" type="radio" name="historical-figures-2" />
copypasta? duplicate id, inexplicable name.

2018-11-27 14:33 UTC, dubharmonic commented on web-client/src/components/ValidateCase.jsx
> +                  <input id="paygov" type="radio" name="historical-figures-2" />
fixed

2018-11-27 16:04 UTC, kkoskelin approved these changes

2018-11-27 16:06 UTC, merged