DevEx: ESLint / Babel refactors and fixes
ustaxcourt/ef-cms-flexion pull request #2488
Opened 2019-07-23 21:06 UTC by ericsorenson

In preparation for a consolidated `package.json`

2019-07-24 12:30 UTC, rachaelparris approved these changes

2019-07-24 17:00 UTC, kkoskelin commented on web-api/src/cases/practitionerCaseAssociationLambda.js
> +    const { caseId } = event.pathParameters || {};
These two statements *could* be combined.

2019-07-24 17:01 UTC, kkoskelin commented on web-api/src/cases/verifyCaseForUserLambda.js
> +    const { caseId } = event.pathParameters || {};
These could also be combined.

2019-07-24 17:01 UTC, kkoskelin commented on web-api/src/cases/verifyPendingCaseForUserLambda.js
> +    const { caseId } = event.pathParameters || {};
combine?

2019-07-24 17:08 UTC, kkoskelin requested changes
Some inconsistencies which do not originate with your authorship, but I feel ought to be addressed.  Or tell me I'm nuts. 🔩

2019-07-24 17:08 UTC, kkoskelin commented on web-api/src/documents/virusScanPdfLambda.js
> +    const { documentId } = event.pathParameters;
Other lambdas in this changeset are using the construction ` ... = event.pathParameters || {}`.
Should this one also do this? Or is this unnecessary here (or everywhere)?

2019-07-24 17:08 UTC, kkoskelin commented on web-api/src/workitems/getDocumentQCBatchedForSectionLambda.js
> +    const { section } = event.pathParameters;
Should this use `event.pathParameters || {}` ?

2019-07-24 17:08 UTC, kkoskelin commented on web-api/src/workitems/getDocumentQCBatchedForUserLambda.js
> +    const { userId } = event.pathParameters;
Should this use `event.pathParameters || {}` ?

2019-07-24 17:08 UTC, kkoskelin commented on web-api/src/workitems/getDocumentQCInboxForSectionLambda.js
> +    const { section } = event.pathParameters;
Should this use `event.pathParameters || {}` ?

2019-07-24 17:08 UTC, kkoskelin commented on web-api/src/workitems/getDocumentQCInboxForUserLambda.js
> +    const { userId } = event.pathParameters;
Should this use `event.pathParameters || {}` ?

2019-07-24 17:08 UTC, kkoskelin commented on web-api/src/workitems/getDocumentQCServedForSectionLambda.js
> +    const { section } = event.pathParameters;
Should this use `event.pathParameters || {}` ?

2019-07-24 17:08 UTC, kkoskelin commented on web-api/src/workitems/getDocumentQCServedForUserLambda.js
> +    const { userId } = event.pathParameters;
Should this use `event.pathParameters || {}` ?

2019-07-24 17:08 UTC, kkoskelin commented on web-api/src/workitems/getInboxMessagesForSectionLambda.js
> +    const { section } = event.pathParameters;
Should this use `event.pathParameters || {}` ?

2019-07-24 17:08 UTC, kkoskelin commented on web-api/src/workitems/getInboxMessagesForUserLambda.js
> +    const { userId } = event.pathParameters;
Should this use `event.pathParameters || {}` ?

2019-07-24 17:08 UTC, kkoskelin commented on web-api/src/workitems/getSentMessagesForSectionLambda.js
> +    const { section } = event.pathParameters;
Should this use `event.pathParameters || {}` ?

2019-07-24 17:08 UTC, kkoskelin commented on web-api/src/workitems/getSentMessagesForUserLambda.js
> +    const { userId } = event.pathParameters;
Should this use `event.pathParameters || {}` ?

2019-07-24 17:08 UTC, kkoskelin commented on web-api/src/workitems/setWorkItemAsReadLambda.js
> +    const { workItemId } = event.pathParameters;
Should this use `event.pathParameters || {}` ?

2019-07-25 14:06 UTC, kkoskelin approved these changes
![](https://media1.tenor.com/images/a2bff3114208b32144df25e68c3ed9f6/tenor.gif?itemid=5692550)

2019-07-27 03:36 UTC, wbyoko approved these changes
![](https://media0.giphy.com/media/14Xx5B178hibS/giphy.gif)

2019-07-31 13:39 UTC, kkoskelin commented on web-api/src/cases/generateDocketRecordPdfLambda.js
> +const { getUserFromAuthHeader } = require('../middleware/apiGatewayHelper');
Yow, could be combined with other import from same file.

2019-07-31 13:54 UTC, kkoskelin commented on cypress/integration/file-a-answer.spec.js
> +describe('Filing an Answer', function() {
I thought this file was deleted in a recent PR?

2019-07-31 13:59 UTC, kkoskelin commented on cypress/support/database.js
> +const data = require('../../web-api/storage/fixtures/seed');
a cypress screenshot is being checked in, but that folder should probably be ignored. (I couldn't add this comment to it but it's at https://github.com/flexion/ef-cms/pull/2488/files?short_path=58060ad#diff-58060ada3e6606b78cda52e2d0325bc8 )

2019-07-31 19:47 UTC, kkoskelin approved these changes
![](https://media3.giphy.com/media/l4EoZ2jube5NoxAAw/giphy.gif)

2019-07-31 20:03 UTC, merged