More computeds
ustaxcourt/ef-cms-flexion pull request #261
Opened 2018-12-04 22:10 UTC by dubharmonic

2018-12-04 22:46 UTC, sadlerw approved these changes

2018-12-05 00:12 UTC, kkoskelin approved these changes
Nice.

2018-12-05 00:34 UTC, dknesek requested changes

2018-12-05 00:34 UTC, dknesek commented on web-client/src/components/ValidateCase.jsx
>                      {caseDetail.irsSendDate && (
Since this is a boolean used to make something visible, I recommend using an "xVisible" kind of variable such as `petitionToIrsSendDateIsVisible`. Imagine you are writing a test of the cerebral UI. What would you want to assert about the UI? Would you assert that the send date isn't null, or that the `petitionToIrsSendDateIsVisible`? Remember, Cerebral is the presenter; a virtual UI.

2018-12-05 00:34 UTC, dknesek commented on web-client/src/components/ValidateCase.jsx
>                      {!caseDetail.irsSendDate && <span>{item.status}</span>}
What is the item here? Imagine its name is "foo". This expression `!caseDetail.irsSendDate` should just be `fooIsVisible`.

2018-12-05 00:34 UTC, dknesek commented on web-client/src/components/ValidateCase.jsx
>                {caseDetail.payGovId && !form.paymentType && (
This expression `caseDetail.payGovId && !form.paymentType` should just be `payGovPaymentDateVisible`.

2018-12-05 00:34 UTC, dknesek commented on web-client/src/components/ValidateCase.jsx
> +                      <span>R served on {caseDetail.irsDateFormatted}</span>
Because concatenation is logic that can sometimes break, _consider_ putting the entire string that is being concatenated, `R served on {caseDetail.irsDateFormatted}`, in one computed value such as `datePetitionSentToIrsMessage` .

2018-12-05 17:18 UTC, dknesek approved these changes

2018-12-05 17:41 UTC, kkoskelin approved these changes
![](https://i.imgur.com/18xQ5bn.gif)

2018-12-05 18:08 UTC, merged