Moved getDocumentUploadPolicy
ustaxcourt/ef-cms-flexion pull request #265
Opened 2018-12-05 19:36 UTC by dubharmonic

2018-12-05 21:48 UTC, kkoskelin approved these changes

2018-12-06 01:45 UTC, codyseibert approved these changes

2018-12-06 02:47 UTC, dknesek reviewed
Is this a step in the direction of getting all the S3 persistence logic encapsulated into the S3 persistence gateway? Or is this the finished product.

@dubharmonic I need to know what should assume when reviewing this.

2018-12-06 03:31 UTC, dknesek requested changes
Is this a step in the direction of getting all the S3 persistence logic encapsulated into the S3 persistence gateway? Or is this the finished product.

@dubharmonic I need to know what should assume when reviewing this.

UPDATE: I assumed you were finished in case you needed to work on this before I got back into it,

2018-12-06 03:31 UTC, dknesek commented on shared/src/business/useCases/uploadCasePdfs.js
> +  const policy = await applicationContext
This call should be moved behind the S3 createPetitionFiles(caseInitiatorData) function.

2018-12-06 03:31 UTC, dknesek commented on shared/src/business/useCases/uploadCasePdfs.js
> +  const petitionDocument = await applicationContext
This call should be moved behind the S3 createPetitionFiles(caseInitiatorData) function.

2018-12-06 03:31 UTC, dknesek commented on shared/src/business/useCases/uploadCasePdfs.js
> +    .createDocumentMetadataRequest({
This call should be moved behind the S3 createPetitionFiles(caseInitiatorData) function.

2018-12-06 03:31 UTC, dknesek commented on shared/src/business/useCases/uploadCasePdfs.js
> +    .createDocumentMetadataRequest({
This call should be moved behind the S3 createPetitionFiles(caseInitiatorData) function.

2018-12-06 03:31 UTC, dknesek commented on shared/src/persistence/awsS3Persistence.js
> +exports.createDocumentMetadataRequest = async ({
This should be a private function.

2018-12-06 03:31 UTC, dknesek commented on shared/src/persistence/awsS3Persistence.js
> +exports.getDocumentUploadPolicy = async ({ applicationContext }) => {
This should be a private function.

2018-12-06 19:54 UTC, dknesek reviewed
Excellent.

2018-12-06 19:54 UTC, dknesek commented on shared/src/persistence/awsS3Persistence.js
> +  const petitionDocumentId = Document.generateUuid();
Can we create a generic helper object to make UUIDs, or even import the UUID lib directly into this module? Calling this on Document is weird. This is something that is done for everything that gets uploaded to S3, whether its a Document or not. It's an S3 persistence thing, not a Document thing.

2018-12-06 19:54 UTC, dknesek commented on web-client/src/main/actions/createCase.js
> +    petitionDocumentId,
How do you know that these are in the right order? I was expecting this to be some sort of data structure like a map that explicitly associates our document types with the UUIDs. Feels brittle to me.

2018-12-06 20:39 UTC, dubharmonic commented on shared/src/persistence/awsS3Persistence.js
> +  const petitionDocumentId = Document.generateUuid();
You're definitely right, I moved it.

2018-12-06 20:44 UTC, dubharmonic commented on web-client/src/main/actions/createCase.js
> +    petitionDocumentId,
Order doesn't matter, because we're using object destructuring https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring

2018-12-06 20:50 UTC, sadlerw approved these changes

2018-12-06 20:54 UTC, dknesek approved these changes

2018-12-06 21:00 UTC, merged