Devex html pdf templates
ustaxcourt/ef-cms-flexion pull request #2912
Opened 2019-08-27 21:41 UTC by matthopson

2019-08-27 21:51 UTC, kkoskelin commented on shared/src/business/utilities/generateHTMLTemplateForPDF.js
> +    oldAddress = `<div>${oldData.phone}</dvi>`;
oops `</dvi>`

2019-08-27 21:51 UTC, kkoskelin commented on shared/src/business/utilities/generateHTMLTemplateForPDF.js
> +      oldAddress += `<div style="margin-top:8px;">${oldData.phone}</dvi>`;
another pair of `</dvi>`

2019-08-27 21:59 UTC, kkoskelin commented on shared/src/business/utilities/generateHTMLTemplateForPDF.test.js
> +    expect(result.indexOf('Test Case Caption')).toBeGreaterThan(-1);
I believe most of the `.indexOf(string) > -1)` comparisons can generally be replaced with `.contains(string)`

2019-08-27 22:03 UTC, kkoskelin requested changes
Just a few typos to address to ensure valid HTML.
Eric mentioned to me at one time that perhaps we could consider using PUG templates, which I think would be a good idea.  That's not a directive for this PR, but just an observation. :)

2019-08-28 13:26 UTC, matthopson commented on shared/src/business/utilities/generateHTMLTemplateForPDF.test.js
> +    expect(result.indexOf('Test Case Caption')).toBeGreaterThan(-1);
<img width="196" alt="Screen Shot 2019-08-28 at 7 25 18 AM" src="https://user-images.githubusercontent.com/1891789/63859767-2324b980-c965-11e9-8543-e4600aa0b289.png">
I don't think .contains is the droids, haha.

2019-08-28 13:52 UTC, matthopson commented
@kkoskelin I'm reverting the change to `includes` (assume what you meant by `contains`) since it's technically not supported in IE11, and polyfills just use indexOf anyway.

2019-08-28 16:03 UTC, kkoskelin commented on shared/src/business/utilities/generateHTMLTemplateForPDF.test.js
> +    expect(result.indexOf('Test Case Caption')).toBeGreaterThan(-1);
You're right, I meant `.includes`, d'oh NBD

2019-08-28 16:05 UTC, kkoskelin approved these changes

2019-08-28 21:46 UTC, merged