Attach Respondent into to Case on Answer Filed
ustaxcourt/ef-cms-flexion pull request #296
Opened 2018-12-11 19:30 UTC by codyseibert

2018-12-11 21:21 UTC, kkoskelin approved these changes

2018-12-11 21:21 UTC, kkoskelin commented on shared/src/business/useCases/respondent/fileAnswer.interactor.test.js
> +    expect(updateCaseStub.getCall(0).args[0].caseDetails.respondent).toEqual({
could you simply compare to MOCK_USER?

2018-12-12 03:27 UTC, dknesek reviewed
This is great work, but I think it exposed some issues we need to iron out.

2018-12-12 03:27 UTC, dknesek commented on shared/src/business/entities/Case.js
> +    respondent: joi.object().keys({
Why wouldn't we create a "Respondent" entity that has this responsibility? That is, when the case it created it plucks this part of the JSON out and creates a new Respondent that validates this. The Case holds a reference to an instance of the respondent entity.

As an aside but related comment, the domain model seems too flat here. I feel like we should have Case --> Answer <-- Repondent.

2018-12-12 03:27 UTC, dknesek commented on shared/src/business/useCases/respondent/associateRespondentToCase.interactor.js
> +  new Case(caseToAssociate).validate();
Is there any reason to think getCase() could return an invalid case?

2018-12-12 03:27 UTC, dknesek commented on shared/src/business/useCases/respondent/associateRespondentToCase.interactor.js
> +  const user = await applicationContext.getUseCases().getUser(userId);
At some point, the currently logged in user should be accessible directly from the application context `applicationContext.getUser()`

2018-12-12 03:27 UTC, dknesek commented on shared/src/business/useCases/respondent/associateRespondentToCase.interactor.js
> +  await applicationContext.getUseCases().updateCase({
We are calling `updateCase` here. I would expect this to just call a persistence method `getPersistenceGateway().associateAnswerToCase(caseId, answerData, respondentData)` that knows how an answer and respondent manifest in Dynamo. This keeps `updateCase` from becoming this super-method that knows all the nuances of updating case related data in every situation. Makes sense to me to have more targeted persistence functions.

2018-12-12 03:27 UTC, dknesek commented on shared/src/business/useCases/respondent/associateRespondentToCase.interactor.js
> +  await applicationContext.getPersistenceGateway().createRespondentCaseMapping({
This "mapping" would be built into the persistence method I described in the previous comment.

2018-12-12 03:27 UTC, dknesek commented on shared/src/business/useCases/respondent/fileAnswer.interactor.js
>    const answerDocumentMetadata = {
It feels like we've complicated things here. I would expect one use case interactor to be called after the S3 upload, `AssociateAnswerToCase`, that manages all the rest. I think our treating "use cases" as function feels like its right, but it's going to create a chatty and messy situation.

2018-12-12 04:57 UTC, codyseibert commented on shared/src/business/useCases/respondent/fileAnswer.interactor.js
>    const answerDocumentMetadata = {
so maybe AssociateAnswerToCase should hit an endpoint POST@/v1/cases/:caseId/answer and have that endpoint hook everything together?

2018-12-12 05:00 UTC, codyseibert commented on shared/src/business/useCases/respondent/associateRespondentToCase.interactor.js
> +  new Case(caseToAssociate).validate();
I guess not if we are always validating what is written.  Are you saying we can just remove this?

2018-12-12 13:33 UTC, dknesek approved these changes

2018-12-12 13:49 UTC, sadlerw requested changes

2018-12-12 13:49 UTC, sadlerw commented on shared/src/business/entities/Case.js
> +      userId: joi.string().optional(),
respondentId might be a better name here

2018-12-12 16:27 UTC, codyseibert commented on shared/src/business/entities/Case.js
> +      userId: joi.string().optional(),
fixed

2018-12-12 19:32 UTC, closed without merging