1942 - editing stipulated decision
ustaxcourt/ef-cms-flexion pull request #2992
Opened 2019-09-05 21:01 UTC by codyseibert

2019-09-05 21:29 UTC, kkoskelin commented on web-client/src/presenter/actions/setPDFForSigningAction.js
> +    documentId: documentIdToLoad,
unsure of the utility of this change

2019-09-05 21:34 UTC, ericsorenson approved these changes

2019-09-05 21:38 UTC, kkoskelin requested changes
Possibly some tech with more logic appearing in components than is probably necessary

2019-09-05 21:38 UTC, kkoskelin commented on web-client/src/views/DraftDocuments/DraftDocuments.jsx
> +                        draftDocument.documentType === 'Stipulated Decision'
I would prefer to see this logic in a computed.

2019-09-05 21:38 UTC, kkoskelin commented on web-client/src/views/PDFSigner.jsx
> +                        display:
I don't know if there's something else going on here with document scopes that I don't know, but I would also prefer that a computed dictate a `className` here rather than a ternary expression toggling an inline style value.

2019-09-06 15:51 UTC, kkoskelin approved these changes

2019-09-06 16:17 UTC, merged