2470 error messages matt
ustaxcourt/ef-cms-flexion pull request #3072
Opened 2019-09-13 20:01 UTC by matthopson

2019-09-13 20:11 UTC, codyseibert approved these changes

2019-09-13 20:32 UTC, kkoskelin requested changes
Big changeset, just a few sharp corners to sand off and we're good!

2019-09-13 20:32 UTC, kkoskelin commented on shared/src/business/entities/CaseAssociationRequestFactory.js
> +          'Certificate of Service date cannot be in the future.. Enter a valid date.',
Two periods should be one.

2019-09-13 20:32 UTC, kkoskelin commented on shared/src/business/entities/cases/Case.js
> +        'The IRS notice date cannot be in the future.. Enter a valid date.',
two periods

2019-09-13 20:32 UTC, kkoskelin commented on shared/src/business/entities/cases/Case.js
> +        'The Fee Payment date cannot be in the future.. Enter a valid date.',
two periods

2019-09-13 20:32 UTC, kkoskelin commented on shared/src/business/entities/contacts/PetitionerCorporationContact.js
> +    inCareOf: 'Enter name of in care of',
odd phrasing?

2019-09-13 20:32 UTC, kkoskelin commented on shared/src/business/entities/contacts/PetitionerDeceasedSpouseContact.js
> +      inCareOf: 'Enter name of in care of',
odd phrasing?

2019-09-13 20:32 UTC, kkoskelin commented on shared/src/business/entities/docketEntry/DocketEntryFactory.js
> +          'Certificate of Service date cannot be in the future.. Enter a valid date.',
two periods

2019-09-13 20:32 UTC, kkoskelin commented on shared/src/business/entities/docketEntry/DocketEntryFactory.js
> +        message: 'Received date cannot be in the future.. Enter a valid date.',
two periods

2019-09-13 20:32 UTC, kkoskelin commented on shared/src/business/entities/docketEntry/DocketEntryFactory.test.js
> +        'Received date cannot be in the future.. Enter a valid date.',
two periods

2019-09-13 20:32 UTC, kkoskelin commented on shared/src/business/entities/docketEntry/DocketEntryFactory.test.js
> +            'Certificate of Service date cannot be in the future.. Enter a valid date.',
two periods

2019-09-13 20:32 UTC, kkoskelin commented on shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.js
> +          'Certificate of Service date cannot be in the future.. Enter a valid date.',
two periods

2019-09-13 20:32 UTC, kkoskelin commented on shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.test.js
> +          'Certificate of Service date cannot be in the future.. Enter a valid date.',
two periods
Probably want to just global search/replace, I'll stop tagging these :)

2019-09-13 20:32 UTC, kkoskelin commented on web-client/integration-tests/journey/docketClerkStartsNewMessageThreadOnAnswer.js
> +      section: 'Select a section.',
probably isn't supposed to end with a period (per replacements spreadsheet).

2019-09-13 20:32 UTC, kkoskelin commented on web-client/integration-tests/journey/docketClerkStartsNewMessageThreadOnStipulatedDecisionToSeniorAttorney.js
> +      section: 'Select a section.',
probably isn't supposed to end with a period (per replacements spreadsheet).
suggesting a global search through changeset for other occurrences

2019-09-13 20:32 UTC, kkoskelin commented on web-client/src/views/StartCase/Address.jsx
> +            aria-label="ZIP code"
For `aria-label`s, this was deliberately written in lower-case to allow the screenreader like MacOS Voiceover read it as a word ("zip code") rather than spelling it out to the user ("zee eye pee code").  I would like this changed back to lower-case, please. (it is a non-visual attribute)

2019-09-17 13:12 UTC, sutt0n commented on shared/src/business/entities/contacts/PetitionerCorporationContact.js
> +    inCareOf: 'Enter name of in care of',
`Enter name of caregiver/caretaker` or similar?

2019-09-17 15:17 UTC, matthopson commented
@kkoskelin Updated.

2019-09-17 18:21 UTC, kkoskelin approved these changes
![](https://media1.tenor.com/images/78b9cc43706c49fadf85fee50243ed47/tenor.gif)

2019-09-17 18:29 UTC, merged