2397 cleanup
ustaxcourt/ef-cms-flexion pull request #3166
Opened 2019-10-02 19:16 UTC by matthopson

Update Request Access form to match File A Document

2019-10-02 19:41 UTC, kkoskelin commented on shared/src/business/entities/CaseAssociationRequestFactory.test.js
> +  let errors = () =>
This can probably stay as `const`, yes?

2019-10-02 19:42 UTC, matthopson commented on shared/src/business/entities/CaseAssociationRequestFactory.test.js
> +  let errors = () =>
Ah yes. I was trying something out and forgot to put it back

2019-10-02 19:43 UTC, codyseibert approved these changes

2019-10-02 20:06 UTC, kkoskelin requested changes
Would prefer a change to some CSS definitions if we could manage it.

2019-10-02 20:06 UTC, kkoskelin commented on web-client/src/styles/overrides.scss
> +  margin-bottom: .5em !important;
Is there a way we can avoid using `!important` but instead modify the selector so that its precedence ensures obedience to `margin-bottom`?  (same for `margin-bottom-0` on line 5)

2019-10-02 20:18 UTC, matthopson commented on web-client/src/styles/overrides.scss
> +  margin-bottom: .5em !important;
I think we'd have to find all the places where `margin-bottom-0` is being ignored and create a specific class / selector for this.

The issue is USWDS gives us handy layout classes, but then overwrites them with element-specific classes later. You'd think layout modifiers would be declared _AFTER_ general element classes so they could do their job, but you can see in USWDS where `usa-form-group`, which is declared _after_ `margin-bottom-x`, has a margin bottom - so you can't override it with their built-in overrides.

I would rather just fix the one I introduced since I'm sure of of what effect it will have.

2019-10-03 14:22 UTC, sutt0n approved these changes

2019-10-03 14:22 UTC, kkoskelin requested changes
I think the css re-definition bears some re-examination.  Unless there is a remarkable reason for using the strategy, I'd like to see it changed.

2019-10-03 14:22 UTC, kkoskelin commented on web-client/src/styles/overrides.scss
> +    margin-bottom: .5em;
I do not believe we should be attempting to redefine the way `.margin-bottom-1` is defined, neither by units nor values.  Best thing would be to change the `.margin-bottom-(?)` class being used beside the `.usa-form-group` anywhere it is found.

2019-10-03 14:27 UTC, matthopson commented on web-client/src/styles/overrides.scss
> +    margin-bottom: .5em;
Because I don't want to play ping pong with this review (holding up other things), I'm just going to remove it completely and create a new PR that addresses the style.

2019-10-03 15:55 UTC, kkoskelin approved these changes

2019-10-03 16:09 UTC, merged