3111 7 printable receipt
ustaxcourt/ef-cms-flexion pull request #3251
Opened 2019-10-09 20:53 UTC by matthopson

2019-10-09 21:19 UTC, rachaelparris commented on web-api/src/documents/generateFilingReceiptPdfLambda.js
> +const customHandle = async (event, fun) => {
Unrelated to this PR, but I think we've used this exact function several times now and it could probably be pulled out into a helper utility.

2019-10-09 21:23 UTC, rachaelparris commented
Is there a need to handle secondary documents? Or is there a reason they weren't included?

2019-10-09 21:26 UTC, rachaelparris commented
You could possibly use the `temp` documents bucket to store this file rather than passing around the blob URL. I'm not sure what that gains you except not having to worry about releasing the blob URL.

2019-10-09 21:38 UTC, kkoskelin commented on web-client/src/presenter/actions/FileDocument/getFileExternalDocumentAlertSuccessAction.js
> +    message = `You can <a href="${props.printReceiptLink}" target="_blank">print a receipt</a> for your filing or access your documents at any time from the docket record below.`;
Not super excited about generating HTML in this manner for display in the success, but I can't think of a better way to do it with the component we've got at this moment.

2019-10-09 21:40 UTC, kkoskelin commented on web-client/src/presenter/actions/FileDocument/getShouldGeneratePrintableFilingReceiptAction.js
> + * Determines if a printable filing receipt should be generated
srsly you get 🏆 for jsdocs.

2019-10-09 21:42 UTC, kkoskelin commented on web-client/src/views/SuccessNotification.jsx
> +  // below the message. TBD.
Agreed -- there's got to be a better way! (what a pain).

2019-10-09 21:43 UTC, kkoskelin approved these changes
Looks like a pretty good first pass.  Likely after some usage we may identify improvements, but I like it.

2019-10-10 12:47 UTC, matthopson commented on web-api/src/documents/generateFilingReceiptPdfLambda.js
> +const customHandle = async (event, fun) => {
Yeah, I wanted to do that when I refactored.

2019-10-10 12:49 UTC, matthopson commented on web-client/src/presenter/actions/FileDocument/getFileExternalDocumentAlertSuccessAction.js
> +    message = `You can <a href="${props.printReceiptLink}" target="_blank">print a receipt</a> for your filing or access your documents at any time from the docket record below.`;
Agreed. I it's my goal to _not_ ship it this way.

2019-10-10 16:09 UTC, matthopson commented
@kkoskelin I've updated the implementation with the link. Chatted with Kristen about moving the link to the bottom of the alert so we can have an optional link inside the component rather than dangerously setting innerHTML.

<img width="678" alt="Screen Shot 2019-10-10 at 10 08 30 AM" src="https://user-images.githubusercontent.com/1891789/66586505-f1973480-eb45-11e9-8c6b-b6a5362580fb.png">

Just going to work on some tests now.

2019-10-10 20:49 UTC, sutt0n requested changes
A few small things. 😄

2019-10-10 20:49 UTC, sutt0n commented on shared/src/proxies/generatePrintableFilingReceiptProxy.js
> + * @param {string} providers.contentHtml the html content for the pdf
JSDoc doesn't match args

2019-10-10 20:49 UTC, sutt0n commented on web-api/serverless-api.yml
> +    handler: web-api/src/apiHandlers.generateFilingReceiptPdfLambda
Why not the `documentsHandlers`?

2019-10-10 20:49 UTC, sutt0n commented on web-client/src/presenter/actions/FileDocument/fileExternalDocumentAction.js
> +    documentsFiled: documentMetadata,
Should this be reflected in this action's corresponding unit test?

2019-10-10 20:49 UTC, sutt0n commented on web-client/src/presenter/actions/FileDocument/generatePrintableFilingReceiptAction.js
> + * @param {object} providers.props the cerebral props object
Prolly should have JSDoc for `providers.get`

2019-10-10 20:49 UTC, sutt0n commented on web-client/src/presenter/actions/FileDocument/getFileExternalDocumentAlertSuccessAction.js
> +  }
Should this be reflected in the unit test?

2019-10-10 20:57 UTC, matthopson commented on web-client/src/presenter/actions/FileDocument/fileExternalDocumentAction.js
> +    documentsFiled: documentMetadata,
We aren't currently testing any of the output from these. Just that the path is called. I'll add something for this.

2019-10-10 20:58 UTC, matthopson commented on web-api/serverless-api.yml
> +    handler: web-api/src/apiHandlers.generateFilingReceiptPdfLambda
This just happens to be where all the other template-generated pdfs are. I can move it over.

2019-10-10 21:29 UTC, sutt0n approved these changes

2019-10-10 21:34 UTC, rachaelparris approved these changes

2019-10-10 21:38 UTC, merged