devex - refactor away if component
ustaxcourt/ef-cms-flexion pull request #3434
Opened 2019-10-29 20:53 UTC by codyseibert

2019-10-29 20:55 UTC, wbyoko requested changes
not sure why this is needed

2019-10-29 20:55 UTC, rachaelparris approved these changes

2019-10-30 13:35 UTC, matthopson approved these changes
@wbyoko Considering there is already a well-established (and well-understood) means of handling conditionals in React templates, I don't really see the need to use a component for this. I may be missing its purpose, though. Happy to discuss, but I'll error on the side of convention.

2019-10-30 14:17 UTC, kkoskelin commented
I'm wondering if we could discuss pro's & con's -- what problem does the `If` component solve and/or what problems are solved by removing it?

2019-10-30 17:09 UTC, sutt0n approved these changes

2019-10-30 20:29 UTC, closed without merging