3516 Enable code splitting
ustaxcourt/ef-cms-flexion pull request #3678
Opened 2019-11-22 20:37 UTC by ericsorenson

enable code splitting, with pdfStyles as an example

2019-11-22 21:57 UTC, matthopson approved these changes

2019-11-25 14:52 UTC, kkoskelin commented on web-client/src/applicationContext.js
> +    const pdfStyles = await import('../../shared/src/tools/pdfStyles.js');
Tell me more about this.

2019-11-25 14:53 UTC, kkoskelin requested changes

2019-11-25 14:53 UTC, kkoskelin commented on web-client/src/applicationContext.js
> +  getPdfStyles: async () => {
Now that this is `async`, you may be needing an `await` in at least one other place (according to my search results)

2019-11-25 16:06 UTC, ericsorenson commented on web-client/src/applicationContext.js
> +  getPdfStyles: async () => {
Updated!

2019-11-25 16:06 UTC, ericsorenson commented on web-client/src/applicationContext.js
> +    const pdfStyles = await import('../../shared/src/tools/pdfStyles.js');
Lazy loading of code keeps the bundle size small.

2019-11-25 16:35 UTC, kkoskelin approved these changes

2019-11-25 16:56 UTC, kkoskelin approved these changes

2019-11-25 17:01 UTC, merged