482 More Modal
ustaxcourt/ef-cms-flexion pull request #3770
Opened 2019-12-04 22:24 UTC by wbyoko

![Screenshot 2019-12-04 16 23 31](https://user-images.githubusercontent.com/1385752/70186872-77e97600-16b2-11ea-9026-7075895f0569.png)

![Screenshot 2019-12-04 16 23 36](https://user-images.githubusercontent.com/1385752/70186871-77e97600-16b2-11ea-9a99-ad619d55326a.png)

![Screenshot 2019-12-04 16 23 47](https://user-images.githubusercontent.com/1385752/70186870-77e97600-16b2-11ea-8899-c19d8d9e87d6.png)

2019-12-04 22:44 UTC, kkoskelin submitted a review, later dismissed
One nitpick, but a couple things really ought to be addressed relating to a11y.  Also, it seems as though the alignment/height of the search input and search button are _off_ a tiny bit.  I wonder if inspection of the search in the header will reveal what's needed.

2019-12-04 22:44 UTC, kkoskelin commented on web-client/src/styles/modals.scss
> +    }
We ought not be altering the behavior of `.usa-sr-only` in this way.  The result is that `display: none` will also NOT be readable by screenreaders or other assistive tech.  The USWDS definition ought to place the element far, far off-screen (absolute position) so as not to influence the rest of this button, I hope.  I'm happy to help if you want to discuss.

2019-12-04 22:44 UTC, kkoskelin commented on web-client/src/views/CaseDetail/AddConsolidatedCaseModal.jsx
> +  <>
the bare `<> ... </>` are probably unnecessary given the enclosing `div`.

2019-12-04 22:44 UTC, kkoskelin commented on web-client/src/views/CaseDetail/AddConsolidatedCaseModal.jsx
> +                aria-describedby="confirm-legend"
Both lines 45 and 50 refer to an element with id `confirm-legend` but no such element exists.
I think probably what you want is `id="confirm-legend"` on line 45.  This will ensure the checkbox gets the label provided on 63, but also extra description provided online 45. (by the way, should this label on 45 actually be a `legend.usa-legend`?)

2019-12-05 04:52 UTC, wbyoko commented on web-client/src/styles/modals.scss
> +    }
okay.

2019-12-05 04:55 UTC, wbyoko commented on web-client/src/views/CaseDetail/AddConsolidatedCaseModal.jsx
> +  <>
yup

2019-12-05 05:02 UTC, wbyoko commented on web-client/src/views/CaseDetail/AddConsolidatedCaseModal.jsx
> +                aria-describedby="confirm-legend"
yup

2019-12-05 13:37 UTC, matthopson commented on web-client/src/presenter/actions/caseConsolidation/setCaseIdFromModalSearchAction.js
> +    caseId: docketNumber,
Why are we setting docketNumber on caseId?

2019-12-05 13:42 UTC, matthopson commented on web-client/src/views/CaseDetail/ModalCaseSearchBox.jsx
> +            <span className="usa-sr-only">Search</span>
Does the text inside the element not get read without adding this?

2019-12-05 15:06 UTC, kkoskelin commented on web-client/src/views/CaseDetail/ModalCaseSearchBox.jsx
> +            <span className="usa-sr-only">Search</span>
`.usa-sr-only` will effectively hide this element from visual users, but the element remains in the document flow and will be read by screenreaders and other assistive tech.

2019-12-05 15:07 UTC, matthopson commented on web-client/src/views/CaseDetail/ModalCaseSearchBox.jsx
> +            <span className="usa-sr-only">Search</span>
But wouldn't `<span className="usa-search-submit-text">Search</span>` be read by screen readers? That's kinda the part I'm confused on.

2019-12-05 15:11 UTC, kkoskelin requested changes
~Much better.  One more thing should be resolved with respect to label / legend.  Ping me if you want to talk about it.~

2019-12-05 15:11 UTC, kkoskelin commented on web-client/src/views/CaseDetail/AddConsolidatedCaseModal.jsx
> +                aria-describedby="confirm-legend"
I'm not certain this is resolved yet.  Line 45 is still a `label` element which uses `htmlFor` referring to an element with id `confirm-legend` which does not exist.  This probably shouldn't be a label. Instead I would suggest something like
`<legend id="confirm-legend"... />`
Otherwise the `aria-describedby` will have no effect.  And I recommend the `label` switch to `legend` (or at least an element which is NOT a label) because inputs & labels generally are delivered in pairs -- and the checkbox already has a label.

2019-12-05 15:12 UTC, kkoskelin approved these changes

2019-12-05 15:12 UTC, kkoskelin commented
Apologies for the errant rejection a moment ago -- I wasn't seeing the update.  All Good!!

2019-12-05 15:19 UTC, kkoskelin commented on web-client/src/views/CaseDetail/ModalCaseSearchBox.jsx
> +            <span className="usa-sr-only">Search</span>
Ha! I was hyper-focused on the one element. I think you're absolutely right.  The `span.usa-sr-only` element can be removed since it is providing no additional semantic information to screenreaders.

2019-12-05 16:07 UTC, merged