482 consolidated cases card
ustaxcourt/ef-cms-flexion pull request #3822
Opened 2019-12-09 21:47 UTC by sutt0n

2019-12-09 21:49 UTC, matthopson commented on shared/src/proxies/getConsolidatedCasesByCaseProxy.js
> +  caseId,
JSDoc

2019-12-09 21:51 UTC, matthopson commented on web-client/src/presenter/actions/caseConsolidation/getConsolidatedCasesByCaseAction.js
> + * @param {object} providers.props the cerebral props object
get

2019-12-09 21:52 UTC, matthopson commented on web-client/src/presenter/actions/caseConsolidation/getConsolidatedCasesByCaseAction.js
> +    consolidatedCases = orderBy(consolidatedCases, 'createdAt', 'asc');
Switch to `Case.sortByDocketNumber(consolidatedCases)`

2019-12-09 21:52 UTC, matthopson commented on web-client/src/presenter/actions/caseConsolidation/getConsolidatedCasesByCaseAction.test.js
> +        caseId: 'case-id-234',
You'll have to add docket numbers on this when you switch the sort method.

2019-12-09 21:54 UTC, matthopson approved these changes
Couple of small things, and then 👍

2019-12-09 22:03 UTC, wbyoko approved these changes

2019-12-09 22:50 UTC, kkoskelin requested changes
Please consider making some asynchronous mocks.  Other than that, just observations about things we can talk about in the future.

2019-12-09 22:50 UTC, kkoskelin commented on shared/src/business/useCases/getConsolidatedCasesByCaseInteractor.test.js
> +    getCasesByLeadCaseIdStub = jest.fn();
Since the original implementation is asynchronous, I would appreciate it if we could use this:
https://jestjs.io/docs/en/mock-function-api.html#mockfnmockresolvedvaluevalue

2019-12-09 22:50 UTC, kkoskelin commented on web-client/src/presenter/actions/caseConsolidation/getConsolidatedCasesByCaseAction.js
> +    store.set(state.caseDetail.consolidatedCases, consolidatedCases);
In attempting to keep our code "clean", one of the reasons we have so many hundreds of actions is often because they were created in pairs, of "fetch something from the api" and then "set it in state".  In your action here, we are combining the two, and admittedly it's not the first time we've done it.  I can't provide a set reason to object to this, but this could be something we talk about in the future (is it really necessary to split them?)

2019-12-09 22:50 UTC, kkoskelin commented on web-client/src/presenter/actions/caseConsolidation/getConsolidatedCasesByCaseAction.test.js
> +        getConsolidatedCasesByCaseInteractor: getConsolidatedCasesByCaseInteractorStub,
Same comment re: `async` : https://jestjs.io/docs/en/mock-function-api.html#mockfnmockresolvedvaluevalue

2019-12-10 13:26 UTC, kkoskelin approved these changes

2019-12-10 13:41 UTC, merged