DevEx: Add CORS limits
ustaxcourt/ef-cms-flexion pull request #3886
Opened 2019-12-16 17:43 UTC by ericsorenson

2019-12-16 18:12 UTC, matthopson approved these changes

2019-12-16 18:55 UTC, rachaelparris approved these changes

2019-12-16 19:08 UTC, codyseibert requested changes
cors for the public endpoints needs to be `ui-public-`

2019-12-16 19:08 UTC, codyseibert commented on web-api/serverless-public-api.yml
> +          cors: ui-${self:provider.stage}.ef-cms.${opt:domain}
I think, and all other "public" api endpoints, needs to be ui-public-${self:provider.... because the public app lives on a separate domain

2019-12-16 19:45 UTC, kkoskelin approved these changes
Once @codyseibert 's point is addressed, good to go

2019-12-17 15:42 UTC, ericsorenson commented on web-api/serverless-public-api.yml
> +          cors: ui-${self:provider.stage}.ef-cms.${opt:domain}
How does this look @codyseibert ?

2019-12-17 16:31 UTC, kkoskelin approved these changes
If it's good with Cody, it's good with me. :)

2019-12-17 16:38 UTC, codyseibert approved these changes

2019-12-17 16:38 UTC, sutt0n approved these changes

2019-12-17 18:16 UTC, merged