Refactor 112/111 Remove Proxied Persistence Methods
ustaxcourt/ef-cms-flexion pull request #389
Opened 2018-12-15 00:05 UTC by sadlerw

2018-12-15 01:30 UTC, codyseibert approved these changes

2018-12-15 02:23 UTC, dknesek requested changes
I coudn't leave this in the code for some reason. This particular comment pertains to the `fileRespondentDocument.js` file:
I'm surprised at how little we use entities to do most of the work in this worker. It seems to be (optimistically) cobbling together JSON and validating the whole thing in one fail swoop using the Case at the end rather than creating a self-validating entity graph and then converting that graph to JSON. I would expect something like this.
```
theCase = new Case(caseToUpdate);
theCase.addDocument(documentType, documentId, userId, filedBy);
theCase.setRespondent(userId);
theCase.addWorkItems(workItems); <--objects
const caseToUpdateRaw = theCase.validateWithError(new UnprocessableEntityError()).toJSON();
await applicationContext.getPersistenceGateway().saveCase({
    userId: user.userId,
    caseToSave: caseToUpdateRaw,
    applicationContext,
});
return caseToUpdateRaw
```
So this worker should be a lot shorter becuase the real workers for much of this are the entities.

2018-12-15 02:23 UTC, dknesek commented on web-client/src/presenter/actions/uploadDocumentAction.js
> +
I was expecting the code from here (although with the specific interactor name as opposed to a dynamic one based on documentType) down to line 38 to be inserted at line 6 just before the end of /shared/src/business/useCases/respondent/fileStipulatedDecision.interactor.js
and /shared/src/business/useCases/respondent/fileAnswer.interactor.js. 

`fileAnswerUpdateCase` will never be used outside of `fileAnswerInteractor` and
`fileStipulatedDecisionUpdateCase` will never be used outside of `fileStipulatedDecision`.

2018-12-15 02:23 UTC, dknesek commented on web-client/src/applicationContext.js
> +  getUseCaseForDocumentUpdate: (documentType, role) => {
Although the dynamics associated with the documentType and role starting at line 70 is muy bueno, this section (58-69) creates unnecessary complexity because these *UpdateCase interactors are coupled to `fileAnswer` and `fileStipulatedDecision` explicitly. (See related comment on line 20 of /web-client/src/presenter/actions/uploadDocumentAction.js.)

2018-12-15 02:23 UTC, dknesek commented on shared/src/business/useCases/respondent/fileStipulatedDecisionUpdateCase.interactor.js
> +      {
It seems "WorkItems" ought to be entity instances here where the constructor validates the contents of the work item and things like the createdAt and updatedAt attributes are defaulted by the entity itself. It feels error-prone to have every object that wants to create work items has to know a work item's data structure and get it right.

2018-12-15 02:23 UTC, dknesek commented on shared/src/business/useCases/respondent/fileRespondentDocument.js
>    workItemsToAdd = [],
This should be a set of WorkItem entities.

2018-12-15 03:53 UTC, codyseibert commented on web-client/src/presenter/actions/uploadDocumentAction.js
> +
I'm not sure what you mean... are you saying make fileAnswerUpdateCase a private method inside the fileAnswerInteractor.interactor.js file?

2018-12-15 04:10 UTC, codyseibert commented on web-client/src/presenter/actions/uploadDocumentAction.js
> +
are you saying you'd rather fileAnswer.interactor.js look like this?

```
 const { fileRespondentDocument } = require('./fileRespondentDocument');

exports.fileAnswer = async ({
  user,
  caseToUpdate,
  document,
  applicationContext,
}) => {
  const documentId = await applicationContext
    .getPersistenceGateway()
    .uploadDocument({
      applicationContext,
      document,
    });

  await fileRespondentDocument({
    userId: user.userId,
    caseToUpdate: {
      ...caseToUpdate,
      documents: [
        ...(caseToUpdate.documents || []),
        {
          documentId,
        },
      ],
    },
    applicationContext,
  });
};
```

2018-12-15 04:58 UTC, dknesek commented on web-client/src/presenter/actions/uploadDocumentAction.js
> +
I'm sure my syntax isn't correct, but the `fileAnswer` interactor gets the `fileAnswerUpdateCase` interactor from the application context and invokes it, returning what it returns. Notice that `getFileAnswerUpdateCase()` is a function, not a property becuase this always gives us more options. I expect that we will soon store the `User` in the application context, at which time these functions may return something different based on the user or thier role.
```
 exports.fileAnswer = async ({
  user,
  caseToUpdate,
  document,
  applicationContext,
}) => {
  const documentId = await applicationContext
    .getPersistenceGateway()
    .uploadDocument({
      applicationContext,
      document,
    });

  return applicationContext
    .getFileAnswerUpdateCase()({
    userId: user.userId,
    caseToUpdate: {
      ...caseToUpdate,
      documents: [
        ...(caseToUpdate.documents || []),
        {
          documentId,
        },
      ],
    },
    applicationContext,
  });
```

2018-12-15 17:53 UTC, codyseibert commented on web-client/src/presenter/actions/uploadDocumentAction.js
> +
So then is the "createCaseAction.js" file incorrect?  That file first calls the "uploadCasePdfs" useCase, and then the "createCase" useCase.  I think we modeled this approach off of the existing approach Eric did.  Should maybe createCaseAction also follow the approach you mention so that there is a single useCase that invokes uploadCasePdfs and createCase?

2018-12-15 17:56 UTC, codyseibert commented on web-client/src/presenter/actions/uploadDocumentAction.js
> +
I think the createCaseAction.js invokes 2 separate useCases, the first one uploads to S3, and the second one updates the case.  We tried to follow that same approach by creating two useCases, fileAnswer (which uploads to s3), and fileAnswerUpdateCase (which updates the case).  Are you saying our existing createCaseAction should also be refactored to instead invoke a single useCase instead of 2 different ones?

2018-12-16 01:17 UTC, dknesek commented on web-client/src/presenter/actions/uploadDocumentAction.js
> +
Yes.

This is something I talked about with Will after he first did it the way we described with `fileAnswer` a week or two ago. His was a better approach than what we did with `createCase` because with his approach the presenter didn't have to know that multiple interactors needed to go together, and you could test the whole use case with one invocation to the parent interactor.

The problem with Will's version, however, is that he also invoked three other interactors in the `fileAnswer` use case as a means of _code reuse_ rather than just for the purpose of _separating S3 uploads_ from the rest. It's the code reuse mechanism that we've been trying to undo recently.

Generally, I think we're playing telephone too much. Things that two of us talk about aren't making there way to everyone's ears. Things are getting lost in the translation and we're doing a bunch of unnecessary rework as a consequence.

2018-12-17 13:31 UTC, merged