1900 - delete a trial session
ustaxcourt/ef-cms-flexion pull request #3944
Opened 2019-12-20 17:53 UTC by codyseibert

2019-12-20 18:21 UTC, rachaelparris commented on web-api/src/trialSessions/deleteTrialSessionLambda.js
> + * creates a new trial session.
Update jsdoc

2019-12-20 18:22 UTC, rachaelparris commented on web-api/src/trialSessions/deleteTrialSessionLambda.js
> + * creates a new trial session.
Update jsdoc

2019-12-20 18:22 UTC, rachaelparris commented on shared/src/business/useCases/trialSessions/deleteTrialSessionInteractor.js
> +
We shouldn't delete a trial session that has already passed, right? Should you also check for that here and throw an error?

2019-12-20 19:41 UTC, kkoskelin commented on shared/src/persistence/dynamo/trialSessions/deleteTrialSessionWorkingCopy.js
> + * @param {object} providers.trialSessionWorkingCopy the trial session working copy data
*jsdoc*

2019-12-20 19:47 UTC, kkoskelin requested changes
Once jsdoc is updated and we're checking for trial sessions' date against current date, good to go.

2019-12-23 14:02 UTC, kkoskelin approved these changes

2019-12-23 16:32 UTC, matthopson commented on shared/src/business/useCases/trialSessions/deleteTrialSessionInteractor.test.js
> +    ).rejects.toThrow('trial session not found');
I feel like we don't use this pattern enough. 👏

2019-12-23 16:32 UTC, matthopson commented on shared/src/business/useCases/trialSessions/deleteTrialSessionInteractor.test.js
> +    ).rejects.toThrow('trial session not found');
(it's usually a try/catch, and then setting an error)

2019-12-23 16:40 UTC, matthopson commented on shared/src/business/useCases/trialSessions/deleteTrialSessionInteractor.test.js
> +        createISODateString: () => '2050-12-01T00:00:00.000Z',
Very brittle. This code is going to fail in 40 years.

2019-12-23 16:43 UTC, rachaelparris approved these changes

2019-12-23 16:46 UTC, matthopson approved these changes

2019-12-23 21:01 UTC, merged