4296: Review Saved Petition edit buttons
ustaxcourt/ef-cms-flexion pull request #4557
Opened 2020-02-25 00:10 UTC by sutt0n

![image](https://user-images.githubusercontent.com/1116426/75202176-16282d80-5730-11ea-8381-279c0808d67e.png)

2020-02-25 15:25 UTC, rachaelparris reviewed
Just a few minor things

2020-02-25 15:25 UTC, rachaelparris commented on web-client/src/presenter/actions/caseDetailEdit/getCaseCaptionForCaseInfoTabAction.test.js
> +  it('should return just the respondent when party type has not been selected', async () => {
This description isn't super clear if you don't know what the contents of `CASE_CAPTION_POSTFIX` are. Maybe `should return just the postfix when party type has not been selected`?

2020-02-25 15:25 UTC, rachaelparris commented on web-client/src/presenter/actions/caseDetailEdit/navigateToEditSavedDocumentDetailAction.js
> + * @param {object} providers.router the riot.router object that is used for changing the route
jsdoc updates

2020-02-25 15:25 UTC, rachaelparris commented on web-client/src/presenter/actions/caseDetailEdit/navigateToEditSavedDocumentDetailAction.test.js
> +  it('does not navigate to the edit saved document detail view if document id is not provided', async () => {
`if the docket number is not provided`

2020-02-25 15:25 UTC, rachaelparris commented on web-client/src/presenter/computeds/formattedCaseDetail.js
> +          editLink = '/edit-saved';
Could you add some a test for this new code?

2020-02-25 17:39 UTC, kkoskelin requested changes
Just a few observations.  Some top work, sir!

2020-02-25 17:39 UTC, kkoskelin commented on web-client/src/presenter/actions/caseDetailEdit/getCaseCaptionForCaseInfoTabAction.js
> + * @param {Function} providers.get the cerebral get function
please add `props` to jsdoc

2020-02-25 17:39 UTC, kkoskelin commented on web-client/src/presenter/actions/caseDetailEdit/navigateToReviewSavedPetitionAction.test.js
> +    routeStub = jest.fn();
👊

2020-02-25 17:39 UTC, kkoskelin commented on web-client/src/presenter/sequences/gotoEditSavedDocumentDetailSequence.js
> +  navigateToEditSavedDocumentDetailAction,
Help me understand -- why do we need to set the current page if we are invoking a route?  Shouldn't the route be responsible for setting its own page?  Or is there some nuance I'm missing?

2020-02-25 17:39 UTC, kkoskelin commented on web-client/src/views/CaseDetailEdit/ReviewSavedPetition.jsx
> +                            Date received
😮

2020-02-26 17:04 UTC, kkoskelin approved these changes

2020-02-26 18:15 UTC, merged