From USTC
ustaxcourt/ef-cms-flexion pull request #4810
Opened 2020-03-24 21:41 UTC by ericsorenson

2020-03-24 21:43 UTC, rachaelparris approved these changes

2020-03-24 21:54 UTC, kkoskelin requested changes
One typo.

2020-03-24 21:54 UTC, kkoskelin commented on docs/SETUP.md
> +A prerequisite for a successful build within CircleCI is [access to CircleCI’s 2 X-large instances](https://circleci.com/pricing/#comparison-table). The memory footprint of the underlying services ar
misspelled `costraints`

2020-03-25 00:45 UTC, kkoskelin approved these changes

2020-03-25 02:26 UTC, merged