Shared app context refactoring
ustaxcourt/ef-cms-flexion pull request #4827
Opened 2020-03-30 13:56 UTC by rachelschneiderman

2020-04-01 18:43 UTC, mrinsin requested changes

2020-04-01 18:43 UTC, mrinsin commented on shared/src/business/useCaseHelper/service/appendPaperServiceAddressPageToPdf.test.js
> +    .generatePaperServiceAddressPagePdf.mockImplementation(
This line could be updated to say `applicationContext
    .getUseCaseHelpers()
    .generatePaperServiceAddressPagePdf.mockResolvedValue(testPdfDoc)` which would then eliminate the need for the `generatePaperServiceAddressPagePdfMock` object, since `generatePaperServiceAddressPagePdf` has already been declared as a jest function in the `createTestApplicationContext` file!

2020-04-01 18:53 UTC, rachelschneiderman commented on shared/src/business/useCaseHelper/service/appendPaperServiceAddressPageToPdf.test.js
> +    .generatePaperServiceAddressPagePdf.mockImplementation(
We are working on fixing these now.

2020-04-02 18:32 UTC, mrinsin approved these changes

2020-04-02 18:33 UTC, merged

2020-04-02 18:33 UTC, rachaelparris approved these changes