4365 practitioner detail
ustaxcourt/ef-cms-flexion pull request #4865
Opened 2020-04-03 19:15 UTC by matthopson

<img width="1425" alt="Screen Shot 2020-04-03 at 1 14 57 PM" src="https://user-images.githubusercontent.com/1891789/78396768-2a700d80-75ad-11ea-9d65-749e3d0766b8.png">

2020-04-03 19:26 UTC, rachaelparris commented on shared/src/business/useCases/practitioners/getPractitionerByBarNumberInteractor.test.js
> +  it('throws an unauthrized error if the request user does not have the MANAGE_ATTORNEY_USERS permissions', async () => {
typo unauthorized

2020-04-03 19:31 UTC, rachaelparris commented on shared/src/business/useCases/practitioners/getPractitionerByBarNumberInteractor.test.js
> +    expect(error).toBeUndefined();
Could you remove the try/catch and this line? If an error is thrown the test will fail, so this isn't necessary.

2020-04-03 19:32 UTC, rachaelparris commented on shared/src/business/useCases/practitioners/getPractitionerByBarNumberInteractor.test.js
> +  it('calls the persistence method to get a private practitioner with the given bar number', async () => {
`to get an IRS practitioner`?

2020-04-03 19:42 UTC, rachaelparris commented on shared/src/business/useCases/practitioners/getPractitionerByBarNumberInteractor.test.js
> +  it('throws a not found error if no pracititoner is found with the given bar number', async () => {
typo practitioner

2020-04-03 19:43 UTC, matthopson commented on shared/src/business/useCases/practitioners/getPractitionerByBarNumberInteractor.test.js
> +  it('throws a not found error if no pracititoner is found with the given bar number', async () => {
I really barfed all over this, didn't I... lol

2020-04-03 19:55 UTC, rachaelparris commented on web-client/src/presenter/sequences/submitPractitionerBarNumberSearchSequence.js
> +  getFormValueBarNumberAction,
This is in here twice

2020-04-03 19:57 UTC, rachaelparris commented on web-client/src/views/PractitionerDetail.jsx
> +    practitionerDetail: state.practitionerDetailHelper,
Could you call this `practitionerDetailHelper` for consistency please?

2020-04-03 19:59 UTC, rachaelparris commented on shared/src/business/useCases/practitioners/getPractitionerByBarNumberInteractor.test.js
> +  it('throws a not found error if no pracititoner is found with the given bar number', async () => {
It's a really hard word to type over and over again!

2020-04-03 19:59 UTC, rachaelparris approved these changes

2020-04-03 20:26 UTC, kkoskelin commented on shared/src/business/useCases/practitioners/getPractitionerByBarNumberInteractor.js
> + * @param {object} userId the id for the user to get
nit: jsdoc update required

2020-04-03 20:38 UTC, kkoskelin commented on web-client/src/presenter/actions/getPractitionerDetailAction.js
> + * @param {object} providers.props the cerebral props object containing the props.barNumber
nit: * get

2020-04-03 21:03 UTC, kkoskelin requested changes
This is a pretty tremendous piece of work, sir.  top notch.
![](https://media.giphy.com/media/57WAdFQc3tba3OkCFZ/giphy.gif)

Just a few things that really ought to be addressed.

2020-04-03 21:03 UTC, kkoskelin commented on web-client/src/presenter/sequences/gotoPractitionerDetailSequence.js
> +    isLoggedIn: [
You might want to show progress
`import { showProgressSequenceDecorator } from '../utilities/sequenceHelpers';`

2020-04-03 21:03 UTC, kkoskelin commented on web-client/src/presenter/sequences/submitPractitionerBarNumberSearchSequence.js
> +    success: [
`showProgress` please

2020-04-03 21:03 UTC, kkoskelin commented on web-client/src/views/PractitionerDetail.jsx
> +                        >
Label elements are meant to be tied to input elements, and then the `htmlFor` attribute is designed to hold the id of the input in question.  For this purpose, we should probably not use `label` elements? (If we're doing this elsewhere, should also be fixed)

2020-04-06 13:57 UTC, codyseibert approved these changes

2020-04-06 14:22 UTC, kkoskelin approved these changes
Only some mild reservations about the label-specific CSS, but nothing concrete to complain about.

2020-04-06 14:22 UTC, kkoskelin commented on web-client/src/presenter/sequences/gotoPractitionerDetailSequence.js
> +      ],
Usually the "success path" is the place where I put the `showProgressSequenceDecorator`, because it is the endpoint that has to fetch, set data. On the other hand if this seems to work as desired, fine by me.

2020-04-06 14:22 UTC, kkoskelin commented on web-client/src/views/PractitionerDetail.jsx
> +                        >
It might be a bit unusual to use "usa-label usa-label-display" for these spans, since they are not actually labels.  I wonder if there's anything better that wasn't originally intended for 'label' tags. Concerned if USWDS messes with margins, padding, etc that your text gets its display altered.

2020-04-06 14:37 UTC, merged

2020-04-06 14:37 UTC, matthopson commented on web-client/src/presenter/sequences/gotoPractitionerDetailSequence.js
> +      ],
In most cases, I've seen the wrapper used around the whole sequence execution.

2020-04-06 14:40 UTC, matthopson commented on web-client/src/views/PractitionerDetail.jsx
> +                        >
Perhaps, but that's the joy of CSS, right? There were a bunch of other instances of this (see https://github.com/flexion/ef-cms/pull/4871). I think the intention was for these to behave like labels, so I would think as long as they still do that - and are using the correct spec'd html element, we'd be ok with what the USWDS does with these classes.

2020-04-06 14:40 UTC, matthopson commented on web-client/src/views/PractitionerDetail.jsx
> +                        >
Perhaps we should add a class that extends the uswds class for instances like this, so it doesn't seem like lies?