Es mapping limit split index
ustaxcourt/ef-cms-flexion pull request #5016
Opened 2020-04-22 21:14 UTC by matthopson

2020-04-22 21:25 UTC, codyseibert approved these changes

2020-04-22 21:47 UTC, ericsorenson commented
Would it have been possible to split this into smaller PRs?

2020-04-23 13:18 UTC, matthopson commented
@ericsorenson I don't think so. The bulk of this PR is tests and seed data updates.

2020-04-23 15:42 UTC, kkoskelin commented on shared/src/business/useCases/processStreamRecordsInteractor.js
> +        entityName: { S: 'Document' },
Can you tell me more about this change?

2020-04-23 15:45 UTC, matthopson commented on shared/src/business/useCases/processStreamRecordsInteractor.js
> +        entityName: { S: 'Document' },
For documents on the case to be processed into the right index, they need an entityName. This code was already doing some "exceptional" things with those documents. I'm just updating it to ensure it has the entityName property.

2020-04-23 15:59 UTC, kkoskelin requested changes
A few questions and a few probably change needed.  But I see where this is going, and I really like it.  Nice work.

2020-04-23 15:59 UTC, kkoskelin commented on web-api/delete-elasticsearch-index.js
> +  ['efcms', 'efcms-case', 'efcms-document', 'efcms-user'].map(async index => {
🚫 warning!  Although you've defined this function as "async", the native `map` implementation will NOT wait for it (nor will a `foreach`).  You'll need to write this as a more traditional loop (e.g. `for (const index in indexes) { await expr; }`

2020-04-23 15:59 UTC, kkoskelin commented on web-api/elasticsearch/elasticsearch-index-settings.js
> +  ['efcms', 'efcms-case', 'efcms-document', 'efcms-user'].map(async index => {
🚫 same caveat applies here -- async won't be applied.

2020-04-23 15:59 UTC, kkoskelin commented on web-api/src/applicationContext.js
> +  User: User,
nbd, nit: any reason to not use the property shorthand of `Document` instead of `Document: Document`, etc?

2020-04-23 17:45 UTC, matthopson commented on web-api/delete-elasticsearch-index.js
> +  ['efcms', 'efcms-case', 'efcms-document', 'efcms-user'].map(async index => {
Addressed

2020-04-23 17:45 UTC, matthopson commented on web-api/elasticsearch/elasticsearch-index-settings.js
> +  ['efcms', 'efcms-case', 'efcms-document', 'efcms-user'].map(async index => {
Addressed

2020-04-23 17:45 UTC, matthopson commented on web-api/src/applicationContext.js
> +  User: User,
Addressed

2020-04-23 18:21 UTC, kkoskelin commented on web-api/delete-elasticsearch-index.js
> +  await Promise.all(
as long as it's not a problem to issue and wait on multiple deletions, this looks like a great solution.

2020-04-23 18:21 UTC, kkoskelin approved these changes

2020-04-23 18:22 UTC, merged