Primary and Docket header components and refactor CoA
ustaxcourt/ef-cms-flexion pull request #5056
Opened 2020-04-30 20:32 UTC by matthopson

Separate PDF header elements and update styles per PDF Style guide in Figma.

<img width="1100" alt="Screen Shot 2020-04-30 at 2 22 01 PM" src="https://user-images.githubusercontent.com/1891789/80756279-73a17780-8aef-11ea-9794-607ab2f827c0.png">

2020-04-30 21:53 UTC, rachaelparris requested changes

2020-04-30 21:53 UTC, rachaelparris commented on shared/src/business/utilities/generateHTMLTemplateForPDF/generateChangeOfAddressTemplate.test.js
> +    console.log(result);
Could you remove this log please?

2020-04-30 21:53 UTC, rachaelparris commented on shared/src/business/utilities/pdfGenerator/components/DocketHeader.jsx
> +          <div id="caption-petitioners">Petitioner(s)</div>
I don't think `Petitioner(s)` can be hardcoded. This part of the string is different depending on the party type. Also `caption` throughout the system now refers to the full caption with `, Petitioner` appended, so I'd like to keep that naming convention straight and change this variable to `caseTitle`.

2020-04-30 21:56 UTC, rachaelparris commented on shared/src/business/utilities/pdfGenerator/components/DocketHeader.jsx
> +          <div id="caption-respondent">Respondent</div>
Should there be some commas in here, before Respondent and before Petitioner? Or are we intentionally leaving out the commas?

2020-04-30 23:04 UTC, matthopson commented on shared/src/business/utilities/pdfGenerator/components/DocketHeader.jsx
> +          <div id="caption-respondent">Respondent</div>
No commas
![Screen Shot 2020-04-30 at 5 04 01 PM](https://user-images.githubusercontent.com/1891789/80767204-9e49fb00-8b04-11ea-8220-30454bb013f6.png)

2020-05-01 00:20 UTC, matthopson commented on shared/src/business/utilities/pdfGenerator/components/DocketHeader.jsx
> +          <div id="caption-petitioners">Petitioner(s)</div>
Man what a ride. I'll be doing some further refactors on this, as it ain't very sustainable.

2020-05-01 14:14 UTC, rachaelparris approved these changes

2020-05-01 14:14 UTC, merged