updated validation on end date- cannot be in the future
ustaxcourt/ef-cms-flexion pull request #5059
Opened 2020-05-01 16:26 UTC by mrinsin

2020-05-01 16:41 UTC, kkoskelin requested changes

2020-05-01 16:41 UTC, kkoskelin commented on shared/src/business/entities/orders/OrderSearch.js
> +        .max('now')
Realizing now that the `OrderSearch.VALID_DATE_SEARCH_FORMATS` is undefined -- so long as the search matches *any* valid date (that isn't in the future) it will pass.
We should perhaps add the desired format to this (currently undefined) array, and then 'splat' it in with
`.format(...OrderSearch.VALID_DATE_SEARCH_FORMATS)`

2020-05-01 17:02 UTC, mrinsin commented on shared/src/business/entities/orders/OrderSearch.js
> +        .max('now')
Ooh, good catch, updating it right now!

2020-05-01 17:08 UTC, mrinsin commented on shared/src/business/entities/orders/OrderSearch.js
> +        .max('now')
Hmm, looks like we don't even need to use the `format()` method in the schema anymore thanks to the `createStartOfDayISO` and `createEndOfDayISO` helper methods that you wrote! Bye bye dead code

2020-05-01 19:43 UTC, mrinsin commented on shared/src/business/entities/orders/OrderSearch.js
> +        .max('now')
Hmm, looks like we don't even need to use the format() method in the schema anymore thanks to the createStartOfDayISO and createEndOfDayISO helper methods that you wrote! Goodbye dead code

2020-05-04 14:12 UTC, rachaelparris approved these changes

2020-05-04 15:21 UTC, kkoskelin approved these changes

2020-05-04 15:56 UTC, merged