4493: Pagination
ustaxcourt/ef-cms-flexion pull request #5404
Opened 2020-06-04 21:18 UTC by sutt0n

<img width="957" alt="image" src="https://user-images.githubusercontent.com/1116426/83811226-039e8800-a67f-11ea-80ad-677ab0609170.png">

2020-06-04 21:27 UTC, rachaelparris commented on shared/src/business/useCases/courtIssuedOrder/updateCourtIssuedOrderInteractor.js
> +    await applicationContext.getPersistenceGateway().saveDocumentFromLambda({
😱

2020-06-04 21:27 UTC, rachaelparris commented on web-client/src/presenter/actions/setCasesAction.test.js
> +        closedeCases: [],
Nit: typo here

2020-06-04 21:27 UTC, rachaelparris commented on web-client/src/presenter/computeds/Dashboard/externalUserCasesHelper.js
> +  const openCases = get(state.formattedOpenCases);
Are these formatted cases coming from another helper? If so, you will run into issues importing it into this helper in this way.

2020-06-04 21:30 UTC, rachaelparris commented
So are all the cases being retrieved by the API, and they're just being limited by the UI? Are there plans to load test this approach?

2020-06-04 22:07 UTC, kkoskelin commented on web-client/src/presenter/actions/Dashboard/incrementCurrentPageClosedCasesAction.test.js
> +      state: { closedCasesCurrentPage: 2 },
probably need to test without `closedCasesCurrentPage` defined for complete coverage.

2020-06-04 22:14 UTC, kkoskelin requested changes
👍  after comments are addressed. Rachael's got an 🦅 👁️

2020-06-04 22:14 UTC, kkoskelin commented on web-client/src/presenter/actions/caseConsolidation/getConsolidatedCasesByUserAction.js
> + * @param {object} providers.get the cerebral get method
Ah, but you removed `get`, so this line can also be removed.

2020-06-04 22:14 UTC, kkoskelin commented on web-client/src/presenter/actions/setCasesAction.js
> + * sets the state.openCases and state.closedCases based on the props.openCaseList passed in
* `and props.closedCaseList`

2020-06-04 22:14 UTC, kkoskelin commented on web-client/src/presenter/computeds/Dashboard/externalUserCasesHelper.js
> +  const openCases = get(state.formattedOpenCases);
Yeah, using a computed in a computed can be bad news. Better off to import helper functions from the file where this originates.

2020-06-05 14:39 UTC, sutt0n commented
@rachaelparris 
> So are all the cases being retrieved by the API, and they're just being limited by the UI? Are there plans to load test this approach?

At first, we were querying Dynamo for cases with a set of caseIds retrieved from the old user-case mapping (just `pk = user|..., sk = case|...`). After a convo with @codyseibert, the user-case mapping was refactored to include details used on the dashboard (so it returns the Docket #, status, createdAt, and leadCaseId instead of the _entire_ aggregated case item).

2020-06-05 14:40 UTC, sutt0n commented on shared/src/business/useCases/courtIssuedOrder/updateCourtIssuedOrderInteractor.js
> +    await applicationContext.getPersistenceGateway().saveDocumentFromLambda({
@kkoskelin and I think this may have been the cause of the intermittent integration tests failing with ES. It'd make sense if the documentContents wasn't being uploaded prior to reindexing and the search being made.

2020-06-05 16:42 UTC, rachaelparris approved these changes

2020-06-05 16:51 UTC, kkoskelin approved these changes

2020-06-05 18:48 UTC, merged