Migration bug fix: Strip leading zeroes in docketNumber
ustaxcourt/ef-cms-flexion pull request #5414
Opened 2020-06-05 17:22 UTC by ericsorenson

2020-06-05 17:23 UTC, kkoskelin approved these changes

2020-06-05 17:27 UTC, rachaelparris approved these changes

2020-06-05 20:50 UTC, kkoskelin commented on shared/src/business/useCases/getCaseInteractor.js
> +  } else {
Same if/else within `getCaseForPublicDocketSearchInteractor` and `getPublicCaseInteractor`

2020-06-05 21:09 UTC, kkoskelin requested changes
I think we need to remove that `isValidDocketNumber` function along with all occurrences which call it.

2020-06-05 21:09 UTC, kkoskelin commented on shared/src/business/useCases/getCaseInteractor.js
> +  } else {
`Case.isValidDocketNumber` is a disease that must be eradicated.

2020-06-06 02:57 UTC, kkoskelin approved these changes
![](https://media1.tenor.com/images/471740095bc336c456301673e2fa3b8a/tenor.gif?itemid=3745439)

2020-06-06 12:39 UTC, merged