402 Remove STIN and RFPOT !!!MERGE 402_frontend FIRST!!!
ustaxcourt/ef-cms-flexion pull request #554
Opened 2019-01-05 20:02 UTC by sadlerw

* clean em out

<img width="554" alt="screen shot 2019-01-05 at 2 01 53 pm" src="https://user-images.githubusercontent.com/2058839/50728622-7ace9600-10f2-11e9-9a4b-9b9d466f5cb7.png">

2019-01-08 03:15 UTC, dknesek requested changes

2019-01-08 03:15 UTC, dknesek commented on shared/src/business/useCases/getCaseTypes.interactor.js
> +  return Case.getCaseTypes();
How does the use case interactor guarantee its contract with the controller/presenter? That is, how does the interactor ensure the structure of the result is valid?

2019-01-08 03:15 UTC, dknesek commented on shared/src/business/useCases/getCaseTypes.interactor.test.js
> +    expect(caseTypes.length).toEqual(12);
How do we test that this function really is working as the caller expects?

2019-01-08 03:15 UTC, dknesek commented on shared/src/business/useCases/getProcedureTypes.interactor.js
> +  return Case.getProcedureTypes();
How does the use case interactor guarantee its contract with the controller/presenter? That is, how does the interactor ensure the structure of the result is valid?

2019-01-08 03:15 UTC, dknesek commented on shared/src/business/useCases/getTrialCities.interactor.js
> +  return Case.getTrialCities(procedureType);
How does the use case interactor guarantee its contract with the controller/presenter? That is, how does the interactor ensure the structure of the result is valid?

2019-01-08 03:15 UTC, dknesek commented on shared/src/business/useCases/getTrialCities.interactor.test.js
> +    expect(caseTypes.length).toEqual(74);
How do we test that this function really is working as the caller expects?

2019-01-09 19:25 UTC, codyseibert approved these changes

2019-01-09 19:57 UTC, merged