406 add all internal users to sendTo
ustaxcourt/ef-cms-flexion pull request #566
Opened 2019-01-07 22:12 UTC by sadlerw

* change interactor to return all internal users by default
* add new action for setting internal users on state
* add retrieve from usecase to document detail sequence
* modify document detail view to loop through users for select/options

2019-01-07 22:18 UTC, codyseibert approved these changes

2019-01-07 22:40 UTC, kkoskelin approved these changes

2019-01-07 23:47 UTC, dknesek requested changes

2019-01-07 23:47 UTC, dknesek commented on shared/src/business/useCases/getUsersInSection.interactor.js
>  exports.getUsersInSection = async section => {
What types of things are allowed as parameters to an interactor?

2019-01-07 23:47 UTC, dknesek commented on shared/src/business/useCases/getUsersInSection.interactor.js
> +    return [
What types of things are allowed (and not allowed) as return values from an interactor?

2019-01-08 16:51 UTC, sadlerw commented
I think we've addressed the PR comments, but will add another PR if not.

2019-01-08 16:51 UTC, merged