refactoring String literals
ustaxcourt/ef-cms-flexion pull request #6168
Opened 2020-08-11 21:49 UTC by mrinsin

2020-08-11 22:11 UTC, rachaelparris approved these changes

2020-08-11 22:13 UTC, kkoskelin commented on web-client/src/presenter/computeds/workQueueSectionHelper.test.js
> +      chambersDisplay(URDAS_CHAMBERS_SECTION.ARMENS_CHAMBERS_SECTION.section),
I presume this is not quite right?

2020-08-11 22:14 UTC, kkoskelin requested changes
I think there was maybe a search/replace whoopsie in just one file. Once addressed, 👍

2020-08-12 18:56 UTC, kkoskelin approved these changes

2020-08-12 19:53 UTC, merged