514 Tabs
ustaxcourt/ef-cms-flexion pull request #673
Opened 2019-01-21 17:11 UTC by dubharmonic

![image](https://user-images.githubusercontent.com/248694/51489220-510da400-1d6d-11e9-9fdf-34863f37c805.png)

2019-01-21 17:28 UTC, codyseibert approved these changes

2019-01-21 17:34 UTC, kkoskelin requested changes
Just a few questions about some possibly stale labels -- if I am mistaken I'm happy to immediately mark as resolved so this can get merged. :)

2019-01-21 17:34 UTC, kkoskelin commented on web-client/src/views/DocumentDetail.jsx
> +                        aria-labelledby="messages-label"
It looks like this might be a stale ID ref. Can you find an object that best describes this and update it?  There may be a few other "aria-labelledby" items in this component that refer to nonexistent elements if you could check them over.  Would be much appreciated!

2019-01-21 19:13 UTC, ericsorenson commented on web-client/src/views/DocumentDetail.jsx
> +                        aria-labelledby="messages-label"
How's this?

2019-01-22 13:00 UTC, kkoskelin approved these changes
![](http://www.reactiongifs.com/wp-content/uploads/2013/01/gandalf_to_the_music.gif)

2019-01-22 15:06 UTC, merged