6882 - Prevent Change of address when case is sealed
ustaxcourt/ef-cms-flexion pull request #6996
Opened 2020-11-04 20:42 UTC by codyseibert

- only generate the pdf, work items, and emails when case is not sealed

2020-11-04 20:53 UTC, mrinsin reviewed
I recall that the `contactPrimary` and `contactSecondary` on a case could have a property called `isAddressSealed`, and that value is set to `true` when a docketClerk seals their address. I'm not certain about this but sealing an address doesn't necessarily seal a case. If that's true, would we need too change all the checks for `case.isSealed` to `case.contactPrimary.isAddressSealed || case.contactSecondary.isAddressSealed`?

2020-11-04 22:33 UTC, kkoskelin approved these changes

2020-11-04 22:41 UTC, mrinsin requested changes
Requesting changes so nobody merges

2020-11-05 18:12 UTC, kkoskelin approved these changes

2020-11-05 18:20 UTC, mrinsin approved these changes

2020-11-05 18:36 UTC, merged