6335: fixing email validation on editing practitioner without email
ustaxcourt/ef-cms-flexion pull request #7846
Opened 2021-02-22 23:01 UTC by rosiehsmith

2021-02-22 23:03 UTC, mrinsin approved these changes

2021-02-23 00:38 UTC, mrinsin requested changes
After thinking about this, I realized we should pass the `validateAddPractitionerSequence` and the `validateUpdatePractitionerSequence` into `PractitionerForm.jsx` as props based on which parent form it is being rendered in, instead of this weird hybrid state of the jsx. I can pair with you tomorrow to work on this!

2021-02-23 00:45 UTC, mrinsin approved these changes

2021-02-23 00:51 UTC, kkoskelin commented
I had to fix some of the commit-hook linting rules earlier today. If you pull in the latest from the develop, I'm hoping that husky will perform the linting and let you know what needs repair.  Additionally, I think @mrinsin has suggestions on ensuring VSCode will format-on-save.

2021-02-23 15:15 UTC, rachaelparris approved these changes

2021-02-23 15:50 UTC, merged