7919: Create EligibleCase entity to whitelist eligible cases data
ustaxcourt/ef-cms-flexion pull request #7960
Opened 2021-03-09 17:31 UTC by sutt0n

This new entity proposes a slimmer entity to address the bug #7919 in which a large payload is being returned on the `eligible-cases` endpoint.

2021-03-09 17:59 UTC, kkoskelin requested changes
Everything looks good so far. Once the interactor tests are up, I'll thumb it. 👍

2021-03-10 14:57 UTC, rachaelparris commented on shared/src/test/mockCase.js
> +      email: 'adam22@yahoo.com',
`example.com` please 😄

2021-03-10 14:58 UTC, rachaelparris commented on shared/src/test/mockCase.js
> +      email: 'thomastorres@yahoo.com',
Also `example.com`

2021-03-10 14:59 UTC, kkoskelin approved these changes
Address comments and we're good to go. 👍

2021-03-10 17:01 UTC, rachaelparris approved these changes

2021-03-10 17:15 UTC, merged