699 qc form contacts
ustaxcourt/ef-cms-flexion pull request #976
Opened 2019-02-28 23:28 UTC by rachaelparris

2019-02-28 23:38 UTC, rachaelparris commented
To do:

* clean up UI spacing/styling
* write tests for resetContactsAction, caseDetailEditContactsHelper, caseDetailEditHelper, and updateCasePartyTypeSequence

2019-03-01 14:45 UTC, kkoskelin requested changes
A handful of things that can be adjusted, but pretty great.

2019-03-01 14:45 UTC, kkoskelin commented on web-client/src/presenter/actions/updatePartyTypeAction.js
>  export const updatePartyTypeAction = async ({ store, props, get }) => {
perhaps add jsdoc here, too, as long as we're touching the file.

2019-03-01 14:45 UTC, kkoskelin commented on web-client/src/presenter/computeds/caseDetailEditContactsHelper.js
> +  return {
this can be simplified as `{contactPrimary, contactSecondary}`

2019-03-01 14:45 UTC, kkoskelin commented on web-client/src/presenter/computeds/caseDetailEditContactsHelper.js
> +  }
I'm wondering if we wish to have a default in this switch block in case none are matched?  Or is it okay for partyType not to match any of the cases and simply return undefined for both? (maybe this is more a requirements question)

2019-03-01 14:45 UTC, kkoskelin commented on web-client/src/presenter/computeds/caseDetailEditHelper.js
> +  return {
could be simplified with
`return {
    ...showContacts,
    partyTypes: PARTY_TYPES,
  };`

2019-03-01 15:16 UTC, rachaelparris commented on web-client/src/presenter/computeds/caseDetailEditHelper.js
> +  return {
These are getting renamed.

2019-03-01 17:02 UTC, kkoskelin approved these changes

2019-03-01 17:37 UTC, codyseibert approved these changes

2019-03-01 17:38 UTC, merged